2024-11-25 18:26:53,123 DEBUG    root            Loaded Command Group: ['gcloud', 'iam']
2024-11-25 18:26:53,125 DEBUG    root            Loaded Command Group: ['gcloud', 'iam', 'roles']
2024-11-25 18:26:53,143 DEBUG    root            Loaded Command Group: ['gcloud', 'iam', 'roles', 'create']
2024-11-25 18:26:53,146 DEBUG    root            Running [gcloud.iam.roles.create] with arguments: [--permissions: "storage.objects.get,storage.objects.create,pubsub.topics.publish,cloudfunctions.functions.invoke", --project: "inspired-photon-441609-k7", --title: "Custom role for needed services", ROLE_ID: "main_custom_role"]
2024-11-25 18:26:53,184 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): iam.googleapis.com:443
2024-11-25 18:26:53,216 DEBUG    urllib3.connectionpool https://iam.googleapis.com:443 "POST /v1/permissions:queryTestablePermissions?alt=json HTTP/1.1" 403 None
2024-11-25 18:26:53,223 DEBUG    root            Chosen display Format:default
2024-11-25 18:26:53,240 DEBUG    root            Chosen display Format:default
2024-11-25 18:26:53,241 DEBUG    root            Chosen display Format:default
2024-11-25 18:26:53,242 DEBUG    root            (gcloud.iam.roles.create) PERMISSION_DENIED: Request had insufficient authentication scopes. This command is authenticated as 644941739395-compute@developer.gserviceaccount.com which is the active account specified by the [core/account] property.
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    method: google.iam.admin.v1.IAM.QueryTestablePermissions
    service: iam.googleapis.com
  reason: ACCESS_TOKEN_SCOPE_INSUFFICIENT

If you are in a compute engine VM, it is likely that the specified scopes during VM creation are not enough to run this command.
See https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam for more information about access scopes.
See https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes for how to update access scopes of the VM.
Traceback (most recent call last):
  File "/snap/google-cloud-cli/275/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/275/lib/googlecloudsdk/calliope/backend.py", line 842, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/275/lib/surface/iam/roles/create.py", line 93, in Run
    permissions_helper = util.PermissionsHelper(client, messages,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/275/lib/googlecloudsdk/api_lib/iam/util.py", line 86, in __init__
    for permission in GetTestablePermissions(iam_client, messages, resource):
  File "/snap/google-cloud-cli/275/lib/third_party/apitools/base/py/list_pager.py", line 120, in YieldFromList
    response = getattr(service, method)(request,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/275/lib/googlecloudsdk/generated_clients/apis/iam/v1/iam_v1_client.py", line 1308, in QueryTestablePermissions
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/275/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/275/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/275/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://iam.googleapis.com/v1/permissions:queryTestablePermissions?alt=json>: response: <{'www-authenticate': 'Bearer realm="https://accounts.google.com/", error="insufficient_scope", scope="https://www.googleapis.com/auth/iam https://www.googleapis.com/auth/cloud-platform"', 'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Mon, 25 Nov 2024 18:26:53 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "service": "iam.googleapis.com",
          "method": "google.iam.admin.v1.IAM.QueryTestablePermissions"
        }
      }
    ]
  }
}
>
2024-11-25 18:26:53,244 ERROR    root            (gcloud.iam.roles.create) PERMISSION_DENIED: Request had insufficient authentication scopes. This command is authenticated as 644941739395-compute@developer.gserviceaccount.com which is the active account specified by the [core/account] property.
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadata:
    method: google.iam.admin.v1.IAM.QueryTestablePermissions
    service: iam.googleapis.com
  reason: ACCESS_TOKEN_SCOPE_INSUFFICIENT

If you are in a compute engine VM, it is likely that the specified scopes during VM creation are not enough to run this command.
See https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam for more information about access scopes.
See https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes for how to update access scopes of the VM.
