2024-11-27 09:01:40,613 DEBUG    root            Loaded Command Group: ['gcloud', 'functions']
2024-11-27 09:01:41,487 DEBUG    root            Loaded Command Group: ['gcloud', 'functions', 'deploy']
2024-11-27 09:01:41,532 DEBUG    root            Running [gcloud.functions.deploy] with arguments: [--entry-point: "gcs_trigger", --runtime: "python312", --set-env-vars: "OrderedDict([('PROJECT_ID', 'inspired-photon-441609-k7'), ('TOPIC_ID', 'gcs-trigger-topic')])", --source: "./pubsub_script", --trigger-event: "google.storage.object.finalize", --trigger-resource: "main-bucket-5505", NAME: "gcs-to-pubsub"]
2024-11-27 09:01:41,700 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudfunctions.googleapis.com:443
2024-11-27 09:01:41,816 DEBUG    urllib3.connectionpool https://cloudfunctions.googleapis.com:443 "GET /v2/projects/inspired-photon-441609-k7/locations/us-central1/functions/gcs-to-pubsub?alt=json HTTP/1.1" 404 None
2024-11-27 09:01:41,820 INFO     ___FILE_ONLY___ As of this Cloud SDK release, new functions will be deployed as 2nd gen  functions by default. This is equivalent to currently deploying new  with the --gen2 flag. Existing 1st gen functions will not be impacted and will continue to deploy as 1st gen functions.
You can disable this behavior by explicitly specifying the --no-gen2 flag or by setting the functions/gen2 config property to 'off'.
To learn more about the differences between 1st gen and 2nd gen functions, visit:
https://cloud.google.com/functions/docs/concepts/version-comparison

2024-11-27 09:01:41,955 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudfunctions.googleapis.com:443
2024-11-27 09:01:42,042 DEBUG    urllib3.connectionpool https://cloudfunctions.googleapis.com:443 "GET /v2/projects/inspired-photon-441609-k7/locations/us-central1/functions/gcs-to-pubsub?alt=json HTTP/1.1" 404 None
2024-11-27 09:01:42,047 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudfunctions.googleapis.com:443
2024-11-27 09:01:42,153 DEBUG    urllib3.connectionpool https://cloudfunctions.googleapis.com:443 "GET /v2/projects/inspired-photon-441609-k7/locations/us-central1/runtimes?alt=json HTTP/1.1" 200 None
2024-11-27 09:01:42,197 INFO     root            Not using ignore file.
2024-11-27 09:01:42,255 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudfunctions.googleapis.com:443
2024-11-27 09:01:42,419 DEBUG    urllib3.connectionpool https://cloudfunctions.googleapis.com:443 "POST /v2/projects/inspired-photon-441609-k7/locations/us-central1/functions:generateUploadUrl?alt=json HTTP/1.1" 200 None
2024-11-27 09:01:42,427 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): storage.googleapis.com:443
2024-11-27 09:01:42,567 DEBUG    urllib3.connectionpool https://storage.googleapis.com:443 "PUT /gcf-v2-uploads-644941739395.us-central1.cloudfunctions.appspot.com/8498dfbb-8b2e-4594-b73e-155ae98ca11f.zip?GoogleAccessId=service-644941739395%40gcf-admin-robot.iam.gserviceaccount.com&Expires=1732699902&Signature=EkwYrmIHl88RSjsjOIxa4kGoO96%2B3LEedTEyJ2PvSAgHPjSNw%2FDlJXDpRsLbcz8pPwdB5dyaODAtGOtPMkNo%2BvZhRqDX3PSjqbOT0j%2Bzol59lJKCbrGJVVszcR%2BhtSKSh6LkHVm0uBbNuOosWG%2BhcNATg64mJSQvDCaFGw0mcxFp2gxaQYMwLrm%2BxjkTt0ZI3RoLmTdyEMfa4gTmCQ4u%2F3mU72IpG%2F9buBh2B7wA4XKZAP3h3DECm1XPMu0KrCpFiSB60CGQ7aQZ0RTz55fuoia0rBWOsaTFzSgEJAMMW4QSC%2BgJnBOD3wxzmWJq86EGaKsa%2Ft65Gy7RfGeil7zaOg%3D%3D HTTP/1.1" 200 0
2024-11-27 09:01:42,659 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): serviceusage.googleapis.com:443
2024-11-27 09:01:42,823 DEBUG    urllib3.connectionpool https://serviceusage.googleapis.com:443 "GET /v1/projects/inspired-photon-441609-k7/services/run.googleapis.com?alt=json HTTP/1.1" 403 None
2024-11-27 09:01:42,827 INFO     root            Could not verify if service run.googleapis.com is enabled: missing permission 'serviceusage.services.get'.
2024-11-27 09:01:42,899 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): serviceusage.googleapis.com:443
2024-11-27 09:01:43,124 DEBUG    urllib3.connectionpool https://serviceusage.googleapis.com:443 "GET /v1/projects/inspired-photon-441609-k7/services/cloudbuild.googleapis.com?alt=json HTTP/1.1" 403 None
2024-11-27 09:01:43,127 INFO     root            Could not verify if service cloudbuild.googleapis.com is enabled: missing permission 'serviceusage.services.get'.
2024-11-27 09:01:43,194 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): serviceusage.googleapis.com:443
2024-11-27 09:01:43,327 DEBUG    urllib3.connectionpool https://serviceusage.googleapis.com:443 "GET /v1/projects/inspired-photon-441609-k7/services/artifactregistry.googleapis.com?alt=json HTTP/1.1" 403 None
2024-11-27 09:01:43,330 INFO     root            Could not verify if service artifactregistry.googleapis.com is enabled: missing permission 'serviceusage.services.get'.
2024-11-27 09:01:43,555 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudbuild.googleapis.com:443
2024-11-27 09:01:43,683 DEBUG    urllib3.connectionpool https://cloudbuild.googleapis.com:443 "GET /v1/projects/inspired-photon-441609-k7/locations/us-central1/defaultServiceAccount?alt=json HTTP/1.1" 200 None
2024-11-27 09:01:43,822 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2024-11-27 09:01:43,916 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "GET /v1/projects/inspired-photon-441609-k7?alt=json HTTP/1.1" 200 None
2024-11-27 09:01:44,053 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2024-11-27 09:01:44,236 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "POST /v1/projects/inspired-photon-441609-k7:getIamPolicy?alt=json HTTP/1.1" 200 None
2024-11-27 09:01:44,248 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudfunctions.googleapis.com:443
2024-11-27 09:01:45,301 DEBUG    urllib3.connectionpool https://cloudfunctions.googleapis.com:443 "POST /v2/projects/inspired-photon-441609-k7/locations/us-central1/functions?alt=json&functionId=gcs-to-pubsub HTTP/1.1" 403 None
2024-11-27 09:01:45,305 DEBUG    root            (gcloud.functions.deploy) ResponseError: status=[403], code=[Ok], message=[Could not create Cloud Run service gcs-to-pubsub. Cannot access API run.googleapis.com in project inspired-photon-441609-k7]
Traceback (most recent call last):
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/api_lib/functions/v1/util.py", line 387, in CatchHTTPErrorRaiseHTTPExceptionFn
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/command_lib/functions/util.py", line 86, in Run
    return self._RunV2(args)
           ^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/surface/functions/deploy.py", line 144, in _RunV2
    return command_v2.Run(args, self.ReleaseTrack())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/command_lib/functions/v2/deploy/command.py", line 1316, in Run
    _CreateAndWait(client, function_ref, function)
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/command_lib/functions/v2/deploy/command.py", line 1140, in _CreateAndWait
    operation = client.projects_locations_functions.Create(create_request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/generated_clients/apis/cloudfunctions/v2/cloudfunctions_v2_client.py", line 122, in Create
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://cloudfunctions.googleapis.com/v2/projects/inspired-photon-441609-k7/locations/us-central1/functions?alt=json&functionId=gcs-to-pubsub>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Wed, 27 Nov 2024 09:01:45 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "Could not create Cloud Run service gcs-to-pubsub. Cannot access API run.googleapis.com in project inspired-photon-441609-k7",
    "status": "PERMISSION_DENIED"
  }
}
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/calliope/backend.py", line 843, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/api_lib/functions/v1/util.py", line 389, in CatchHTTPErrorRaiseHTTPExceptionFn
    core_exceptions.reraise(
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/core/exceptions.py", line 149, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/snap/google-cloud-cli/289/lib/third_party/six/__init__.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/api_lib/functions/v1/util.py", line 387, in CatchHTTPErrorRaiseHTTPExceptionFn
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/command_lib/functions/util.py", line 86, in Run
    return self._RunV2(args)
           ^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/surface/functions/deploy.py", line 144, in _RunV2
    return command_v2.Run(args, self.ReleaseTrack())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/command_lib/functions/v2/deploy/command.py", line 1316, in Run
    _CreateAndWait(client, function_ref, function)
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/command_lib/functions/v2/deploy/command.py", line 1140, in _CreateAndWait
    operation = client.projects_locations_functions.Create(create_request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/googlecloudsdk/generated_clients/apis/cloudfunctions/v2/cloudfunctions_v2_client.py", line 122, in Create
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/289/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
googlecloudsdk.calliope.exceptions.HttpException: ResponseError: status=[403], code=[Ok], message=[Could not create Cloud Run service gcs-to-pubsub. Cannot access API run.googleapis.com in project inspired-photon-441609-k7]
2024-11-27 09:01:45,325 ERROR    root            (gcloud.functions.deploy) ResponseError: status=[403], code=[Ok], message=[Could not create Cloud Run service gcs-to-pubsub. Cannot access API run.googleapis.com in project inspired-photon-441609-k7]
